version: '3'
services:

  database:
    image: postgres
    volumes:      
       - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sqlalchemy
    ports:
      - "5432:5432"
    restart: always
    networks:
      services-network:
        aliases:
          - database

  api:
    build:
      context: .
      dockerfile: ./mltrace/server/Dockerfile
    environment:
      PYTHONPATH: /src
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    env_file:
      - ./.flaskenv
    restart: always
    depends_on:
      - database
    networks:
      services-network:
        aliases:
          - api
  
volumes:  
  postgres_data:

networks:
  services-network:
    name: services-network
    driver: bridge